#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/wmake.cmake-args
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments
. ${WM_PROJECT_DIR:?}/wmake/scripts/have_adios2
# -----------------------------------------------------------------------------

if [ -n "$CMAKE_INSTALL_PREFIX" ]
then
    export CMAKE_INSTALL_PREFIX
fi

#------------------------------------------------------------------------------

if have_adios2
then
    adiosFoam/Allwmake
    adiosWrite/Allwmake
else
    hint_adios2
fi

# -----------------------------------------------------------------------------
